### ISSUE TITLE
no_cache flag not working

### ISSUE THREAD

**Issue by altherlex** [serpapi/google-search-results-ruby#12]
Search should get from cache as doc says no_cache is false by default but it is currently not doing that.

Also, there is no way to retrieve the search_id from previous searches.

**Comment by hartator** [comment]
> Search should get from cache as doc says no_cache is false by default but it is currently not doing that.

@altherlex Can you share a code example of what you mean?

> Also, there is no way to retrieve the search_id from previous searches.

Previous searches should return their own search IDs. 

You can query then SerpApi these ways:
- `https://serpapi.com/searches/{SEARCH_ID}.json?api_key={YOUR_API_KEY}` (Rich JSON)
- `https://serpapi.com/searches/{SEARCH_ID}.html?api_key={YOUR_API_KEY}` (Raw HTMK)

**Comment by jvmvik** [comment]
closing this issue because not enough details was provided.
