### ISSUE TITLE
build error according to the readme badge

### ISSUE THREAD

**Issue by matkoniecz** [serpapi/google-search-results-ruby#2]
see https://github.com/serpapi/google-search-results-ruby#google-search-results-in-ruby

**Comment by hartator** [comment]
It seems to be linked to some new engines we just added:

![image](https://user-images.githubusercontent.com/307597/79506637-f14b8a80-7ffb-11ea-9d05-5e64c4ed6a29.png)

@jvmvik Can you give it a shot at fixing when you have the chance? Thanks.

**Comment by jvmvik** [comment]
The test are passing locally with my personal API key. 
There is an authentication error between TravisCI and our server.

**Comment by jvmvik** [comment]
This issue is finally resolved. We moved to GitHub CI server which allow to provided the encrypted API_KEY missing in TravisCI.
