### ISSUE TITLE
Raise more specific exceptions when API returns an error response

### ISSUE THREAD

**Issue by michalvalasek** [serpapi/google-search-results-ruby#6]
Currently the library raises only a generic `RuntimeError` with message coming from the "error" field in the JSON body of the response. This is very generic and hard to react to.

The library could pass up more information about these error, e.g. by raising more specific exceptions.

**Comment by jvmvik** [comment]
The backend server has been upgraded to provided HTTP code. 
Would like you us to turn the HTTP status code into a Ruby exception ?
for example:
http status: 401 -> UnauthorizedException("body of the http response")
